Update deploy-develop.yml

diff --git a/.github/workflows/deploy-develop.yml b/.github/workflows/deploy-develop.yml
--- a/.github/workflows/deploy-develop.yml
+++ b/.github/workflows/deploy-develop.yml
@@ -23,6 +23,12 @@ jobs:
         echo "PUBLISHED_PORT=$(jq -r .service.published_port configs/develop.json)" >> $GITHUB_ENV
         echo "TARGET_PORT=$(jq -r .service.target_port configs/develop.json)" >> $GITHUB_ENV
 
+        # Verifica se as variáveis de porta estão vazias
+        if [[ -z "${PUBLISHED_PORT}" || -z "${TARGET_PORT}" ]]; then
+          echo "Port configuration is missing in configs/develop.json"
+          exit 1
+        fi
+
         # Criar tag personalizada baseada na hash do commit e data
         IMAGE_TAG=$(echo "${{ github.sha }}" | head -c7)
         echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
@@ -54,11 +60,18 @@ jobs:
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         script: |
-          # Cria o serviço se ele não existir
-          docker service create --name ${{ env.SERVICE_NAME }} \
-                                --publish published=${{ env.PUBLISHED_PORT }},target=${{ env.TARGET_PORT }} \
-                                ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest || \
-          # Atualiza o serviço se ele já existir
-          docker service update \
-                                --publish-add published=${{ env.PUBLISHED_PORT }},target=${{ env.TARGET_PORT }} \
-                                ${{ env.SERVICE_NAME }}
+          # Verifica se as portas foram definidas corretamente
+          if [[ -n "${PUBLISHED_PORT}" && -n "${TARGET_PORT}" ]]; then
+            # Cria o serviço se ele não existir
+            docker service create --name ${{ env.SERVICE_NAME }} \
+                                  --publish published=${{ env.PUBLISHED_PORT }},target=${{ env.TARGET_PORT }} \
+                                  ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest || \
+            # Atualiza o serviço se ele já existir
+            docker service update \
+                                  --publish-rm published=${{ env.PUBLISHED_PORT }},target=${{ env.TARGET_PORT }} \
+                                  --publish-add published=${{ env.PUBLISHED_PORT }},target=${{ env.TARGET_PORT }} \
+                                  ${{ env.SERVICE_NAME }}
+          else
+            echo "Port configuration is missing, skipping service update."
+            exit 1
+          fi
